# Generated by Django 4.0.1 on 2022-02-08 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaraunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField()),
                ('image_label', models.ImageField(blank=True, upload_to='restaraunt_image_label')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_restaraunt', models.BooleanField(default=False)),
                ('unique_code', models.CharField(blank=True, default='', max_length=10)),
                ('balance', models.FloatField(default=0.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='0', max_length=5)),
                ('size', models.IntegerField(default=2)),
                ('time_booking', models.TimeField(default='10:00')),
                ('date_booking', models.DateField(default='01.01.2000')),
                ('is_closed', models.BooleanField(default=False)),
                ('sum', models.FloatField(blank=True, default=0.0)),
                ('restaraunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table', to='app.restaraunt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to='app.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, upload_to='restaraunt_photos')),
                ('restaraunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_file', to='app.restaraunt')),
            ],
        ),
        migrations.CreateModel(
            name='MenuPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, upload_to='restaraunt_menu')),
                ('restaraunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_menu', to='app.restaraunt')),
            ],
        ),
    ]
