# Generated by Django 4.0.1 on 2022-01-25 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaraunt',
            name='image_label',
            field=models.ImageField(blank=True, upload_to='restaraunt_image_label'),
        ),
        migrations.AddField(
            model_name='restaraunt',
            name='menu',
            field=models.ImageField(blank=True, upload_to='restaraunt_menus'),
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='0', max_length=5)),
                ('booking', models.BooleanField(default=False)),
                ('size', models.IntegerField(default=2)),
                ('restaraunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table', to='app.restaraunt')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, upload_to='restaraunt_photos')),
                ('restaraunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_file', to='app.restaraunt')),
            ],
        ),
    ]
