# Generated by Django 4.0.1 on 2022-01-27 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_restaraunt_image_label_restaraunt_menu_table_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaraunt',
            name='Restaraunt label',
        ),
    ]
