# Generated by Django 4.0.1 on 2022-01-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_restaraunt_restaraunt label'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaraunt',
            name='Restaraunt label',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
