# Generated by Django 4.0.1 on 2022-01-27 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_restaraunt_restaraunt label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaraunt',
            old_name='Restaraunt label',
            new_name='name',
        ),
    ]
