# Generated by Django 4.0.1 on 2022-01-27 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_restaraunt label_restaraunt_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaraunt',
            old_name='name',
            new_name='label',
        ),
    ]
