# Generated by Django 4.0.1 on 2022-01-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_name_restaraunt_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='time_booking',
            field=models.TimeField(default='10:00'),
        ),
        migrations.AlterField(
            model_name='restaraunt',
            name='label',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
