# Generated by Django 4.0.1 on 2022-01-29 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_table_time_booking_alter_restaraunt_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='booking',
        ),
    ]
